# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "pipetest" ]
  pull_request:
    branches: [ "main", "pipetest" ]

jobs:
  build:
    runs-on: windows-2022
    # runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET build dependencies
      uses: timheuer/bootstrap-dotnet@v1
      with:
        nuget: 'false'
        sdk: 'false'
        msbuild: 'true'
    - name: Restore dependencies
      run: dotnet restore RevitAddinTemplate.Multiversion.csproj
      working-directory: ./RevitAddinTemplate.Multiversion
    - name: check sdks
      run: dotnet --list-sdks  
    - name: Build zipped Template
      run: msbuild RevitAddinTemplate.Multiversion.csproj /p:Configuration=Release
      # run: dotnet build --no-restore
      working-directory: ./RevitAddinTemplate.Multiversion
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name }}.zip
        path: RevitAddinTemplate.Multiversion/bin/Release/*.zip
    - name: Test
      run: dotnet test --no-build --verbosity normal
