# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore 
    # - name: Install VS CoreUtility
    #   run: dotnet add package Microsoft.VisualStudio.CoreUtility --version 17.9.187
    - name: Build
      run: msbuild /p:Configuration=Release
      # run: dotnet build --no-restore
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name }}.zip
        path: RevitAddinTemplate.Multiversion/bin/Release/*.zip
    - name: Test
      run: dotnet test --no-build --verbosity normal
